VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "BOC"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum BOC

    NS = 0

    Payroll = 10

    FTE = 17

    NonSiteTravel = 21

    SiteTravel = 28

    Expenses = 36

    Contracts = 37

    Grants = 41
    
End Enum

