VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FederalHoliday"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum FederalHoliday

    '/// <summary>
    '/// Creates new years.
    '/// </summary>
    NewYears

    '/// <summary>
    '/// The martin luther king
    '/// </summary>
    MartinLutherKing

    '/// <summary>
    '/// The presidents
    '/// </summary>
    Presidents

    '/// <summary>
    '/// The memorial
    '/// </summary>
    Memorial

    '/// <summary>
    '/// The independence
    '/// </summary>
    Independence

    '/// <summary>
    '/// The veterans
    '/// </summary>
    Veterans

    '/// <summary>
    '/// The labor
    '/// </summary>
    Labor

    '/// <summary>
    '/// The columbus
    '/// </summary>
    Columbus

    '/// <summary>
    '/// The thanksgiving
    '/// </summary>
    Thanksgiving

    '/// <summary>
    '/// The christmas
    '/// </summary>
    Christmas
    
End Enum

