VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FromTo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum FromTo

    '/// <summary>
    '/// Defines the None
    '/// </summary>
    NS = 0

    '/// <summary>
    '/// Defines the From
    '/// </summary>
    Sender = 1

    '/// <summary>
    '/// Defines the To
    '/// </summary>
    Receiver
    
End Enum



