VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FundCode"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum FundCode

    NS = 0

    B

    BR

    BR1

    BR2

    BR3

    T

    TC

    TD

    TR

    TR1

    TR2

    TR2A

    TR2B

    TR3

    TS3

    F

    FC

    FD

    FR

    FS3

    H

    HR

    HC

    HD

    E

    E1

    E1C

    E1D

    E1S3

    E2

    E2C

    E2D

    E3

    E3C

    E3D

    E4

    E4C

    E4D

    E5

    E5C

    E5D

    ZL
End Enum


