VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Level"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum Level

    '/// <summary>
    '/// The ns
    '/// </summary>
    NS = 0

    '/// <summary>
    '/// The region
    '/// </summary>
    Region = 7

    '/// <summary>
    '/// The division
    '/// </summary>
    Division = 8

End Enum



