VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "RPIO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum RPIO

    NS = 0

    R01

    R02

    R03

    R04

    R05

    R06

    R07

    R08

    R09

    R10

    R11

    R13

    R16

    R17

    R18

    R20

    R26

    R30

    R35

    R39

    R75

    R77

    R92

    R94

    R95

    R98

    R9B

    R9H

    R9P

    R9R

    R9V

    R9Z

    HQ

    RT
End Enum

