VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Source"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database


Public Enum Source
    NS = 0
    AccountingEvents
    Appropriations
    Activity
    AppropriationBills
    ARD
    AllowanceHolders
    Allocations
    Accounts
    Awards
    Balances
    BudgetObjectClass
    ControlNumbers
    CategoricalGrants
    CarryOver
    Commitments
    Contracts
    CWSRF
    DivisionAuthority
    DWSRF
    DivisionExecution
    Divisions
    Deobligations
    DeepWaterHorizon
    Documents
    EJ
    Employees
    Expenses
    External
    ECAD
    EPM
    ExternalTransfers
    Expenditures
    Funds
    FTE
    FiscalYears
    FinanceObjectClass
    FullTimeUtilization
    Grants
    Goals
    HumanResourceData
    HumanResourceOrganizations
    InformationTechnology
    InternalTransfers
    LUST
    LCARD
    LSASD
    LeaveProjections
    LustSupplemental
    MSR
    MSD
    NewObligationalAuthority
    NationalPrograms
    NonSiteTravel
    OilSpill
    ORC
    ORA
    Objectives
    Organizations
    Outlays
    Obligations
    OpenCommitments
    Overtime
    PayrollObligations
    ProgramAreas
    Payroll
    PayrollHours
    Procurements
    Payments
    PurchaseActivity
    PRC
    ProgramProjects
    Programs
    Purchases
    Reimbursables
    Requisitions
    ResourcePlanningOffices
    ResponsibilityCenters
    Reprogrammings
    RegionAuthority
    STAG
    SF6A
    Sites
    Superfund
    SpecialAccounts
    SuperfundSupplemental
    SpecialProjects
    SiteTravel
    SEMD
    Supplemental
    Transfers
    TravelObligations
    Travel
    Utilization
    ULO
    Vendors
    WD
    WSA
    WCF
    WorkforceData
    WorkCodes
    XA
End Enum


