CREATE TABLE IF NOT EXISTS "AppropriationDocuments" 
(
	"ID"	INTEGER,
	"BFY"	INTEGER,
	"EFY"	TEXT,
	"Fund"	TEXT,
	"FundCode"	TEXT,
	"DocumentType"	TEXT,
	"DocumentNumber"	TEXT,
	"DocumentDate"	TEXT,
	"LastDocumentDate"	TEXT,
	"BudgetLevel"	INTEGER,
	"BudgetingControls"	TEXT,
	"PostingControls"	TEXT,
	"PreCommitmentControls"	TEXT,
	"CommitmentControls"	TEXT,
	"ObligationControls"	TEXT,
	"AccrualControls"	TEXT,
	"ExpenditureControls"	TEXT,
	"ExpenseControls"	TEXT,
	"ReimbursementControls"	TEXT,
	"ReimbursableAgreementControls"	TEXT,
	"Budgeted"	REAL,
	"Posted"	REAL,
	"CarryOut"	TEXT,
	"CarryIn"	TEXT,
	"EstimatedReimbursements"	REAL,
	"EstimatedRecoveries"	REAL
)